apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-10
  namespace: micro
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/zookeeper-pv/
